### ISSUE TITLE
Target layer configuration for third-party jars

### ISSUE THREAD

**Issue by Su5eD** [MinecraftForge/JarJar#3]
Currently, there is no way of changing the target layer of third-party non-mc jars. Instead, they are all put on the `GAME` layer, making it impossible for language providers to access them.

I'm aware that this issue is known as it was previously mentioned in [MinecraftForge](https://github.com/MinecraftForge/MinecraftForge/issues/8878#issuecomment-1194272189), although I'd like to discuss possible solutions for it.
1. **How do we want to define the target jar layer?**  
   Should the target layer be defined in jarJar metadata, or should we use the manifest `FMLModType` attribute?
2. **How do we want to handle layer selection? Should we account for layer conflicts?**
   SizableShrimp's suggestion was to poll all selection candidates and put the selected jar on the lowest requested layer. However, this might become an issue if a mod wants to apply transformations to that library, but it ends up on the `PLUGIN` layer, making it non-transformable.

**Comment by marchermans** [comment]
This was discussed before.
JarJar is primarily ment for mods, not for ModLauncher plugins.

It has been discussed internally and any change to this has been rejected.
I am sorry as such we won't be implementing this.
